services:
  - type: web
    name: render-fastapi-backend
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -U pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/ping
    envVars:
      - key: APP_NAME
        value: RenderFastAPI
      - key: APP_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://chat.openai.com
